/**
 * daemon/ota.ts — `aibroker ota` subcommands.
 *
 * Manages the aibroker-ota Docker container and Tailscale Serve configuration.
 * The container never touches tailscaled — Tailscale Serve is configured here on the host.
 */

import { execSync, spawnSync } from "node:child_process";
import { existsSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";

/**
 * Where the OTA container listens. Must match docker/compose.yml and
 * docker/ota/src/server.ts.
 *
 * The daemon already owns the two ports below it, so neither is available:
 *   8765  PAILot MQTT broker      (adapters/pailot/mqtt-broker.ts)
 *   8766  Todoist webhook server  (daemon/todoist-webhook.ts)
 * Both are bound by the launchd-managed daemon, which therefore always wins a
 * race against a container. 8767 was verified free — `lsof -nP -iTCP:8760-8790`
 * shows only the two above — before it was chosen. Check again before moving it.
 */
export const OTA_PORT = 8767;

const COMPOSE_FILE = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "docker", "compose.yml");
const ENV_FILE = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "docker", ".env");

function composeExec(args: string[]): void {
  // Say so plainly when the build context is not on disk. `files` in
  // package.json whitelists what ships, and `docker` was not on that list, so
  // every npm install of aibroker carried an `ota` command that could not
  // possibly work — docker compose would fail on a missing file with a message
  // about paths rather than about packaging. Found by unpacking the published
  // tarball rather than by reading the working copy, where it is invisible.
  if (!existsSync(COMPOSE_FILE)) {
    console.error(
      `OTA build context missing: ${COMPOSE_FILE}\n` +
        `  This installation of aibroker did not ship docker/. Run \`aibroker ota\`\n` +
        `  from a git checkout, or reinstall a version that includes it (>= 0.31.1).`
    );
    process.exit(1);
  }

  const result = spawnSync(
    "docker",
    ["compose", "-f", COMPOSE_FILE, ...args],
    { stdio: "inherit", env: { ...process.env } },
  );
  if (result.status !== 0) process.exit(result.status ?? 1);
}

function writeEnv(): void {
  const uid = execSync("id -u", { encoding: "utf-8" }).trim();
  const gid = execSync("id -g", { encoding: "utf-8" }).trim();
  const publishers = process.env.AIBROKER_OTA_PUBLISHERS ?? "";
  writeFileSync(
    ENV_FILE,
    `# Auto-generated by aibroker ota up — do not edit manually\nUID=${uid}\nGID=${gid}\nAIBROKER_OTA_PUBLISHERS=${publishers}\n`,
    "utf-8",
  );
  console.log(`Wrote ${ENV_FILE} (UID=${uid} GID=${gid})`);
}

function ensureDataDirs(): void {
  const base = join(homedir(), ".aibroker", "ota");
  mkdirSync(join(base, "apps"), { recursive: true });
  mkdirSync(join(base, "uploads-tmp"), { recursive: true });
}

function setupTailscaleServe(): void {
  // Idempotent — tailscale serve is safe to run multiple times.
  //
  // Deliberately 8443, not 443. Port 443 carries the Todoist webhook, and that
  // one has to be a Funnel because Todoist calls from the public internet and
  // refuses a URL with a port in it. Funnel is a property of the whole port:
  // anything routed on 443 is public. The OTA hub serves app binaries and an
  // upload API, so it stays on a tailnet-only port of its own.
  //
  // The upstream is 8767, not 8765. 8765 is the daemon's PAILot MQTT broker,
  // and these two mappings used to point at it — so every request Tailscale
  // forwarded on /install/ and /api/ reached an MQTT listener instead of this
  // server. Nothing surfaced it because the container could not bind that port
  // either, so there was never a working case to compare against.
  const cmds = [
    `tailscale serve --bg --https=8443 --set-path=/install/ http://127.0.0.1:${OTA_PORT}/install/`,
    `tailscale serve --bg --https=8443 --set-path=/api/ http://127.0.0.1:${OTA_PORT}/api/`,
  ];
  for (const cmd of cmds) {
    console.log(`+ ${cmd}`);
    try {
      execSync(cmd, { stdio: "inherit" });
    } catch (e) {
      console.warn(`tailscale serve may already be configured: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
}

/**
 * Remove the Serve mappings that `up` created.
 *
 * `down` used to stop the container and leave these behind, which matters
 * because this hub is used in bursts: fire it up, publish a build, tear it
 * down. Between bursts the tailnet kept advertising /install/ and /api/ on
 * :8443 with nothing behind them — and before the port fix they pointed at
 * 8765, so what answered was the PAILot MQTT broker rather than a 502.
 *
 * Each mapping is removed independently; `off` on a path that is already gone
 * is an error we do not care about, so failures are reported and not fatal.
 */
function teardownTailscaleServe(): void {
  const cmds = [
    `tailscale serve --https=8443 --set-path=/install/ off`,
    `tailscale serve --https=8443 --set-path=/api/ off`,
  ];
  for (const cmd of cmds) {
    console.log(`+ ${cmd}`);
    try {
      execSync(cmd, { stdio: "inherit" });
    } catch (e) {
      console.warn(`tailscale serve may already be cleared: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
}

export async function runOta(args: string[]): Promise<void> {
  const [sub, ...rest] = args;

  switch (sub) {
    case "up": {
      writeEnv();
      ensureDataDirs();
      composeExec(["up", "-d", "--build"]);
      console.log("\nConfiguring Tailscale Serve...");
      setupTailscaleServe();
      console.log("\naibroker-ota is up. Run `aibroker ota status` to verify.");
      break;
    }

    case "down": {
      composeExec(["down"]);
      teardownTailscaleServe();
      break;
    }

    case "status": {
      console.log("=== Docker ===");
      composeExec(["ps"]);
      console.log("\n=== Tailscale Serve ===");
      try {
        execSync("tailscale serve status", { stdio: "inherit" });
      } catch {
        console.warn("tailscale serve status failed — is Tailscale running?");
      }
      break;
    }

    case "logs": {
      const follow = rest.includes("-f") || rest.includes("--follow");
      composeExec(follow ? ["logs", "-f", "aibroker-ota"] : ["logs", "aibroker-ota"]);
      break;
    }

    case "setup-serve": {
      setupTailscaleServe();
      break;
    }

    case "teardown-serve": {
      teardownTailscaleServe();
      break;
    }

    default:
      console.error(`Unknown ota subcommand: ${sub ?? "(none)"}`);
      console.error("Usage: aibroker ota [up|down|status|logs|setup-serve|teardown-serve]");
      process.exit(1);
  }
}
