/**
 * a2a/tasks.ts — the Task store behind AIBroker's A2A server.
 *
 * Pure functions over a JSON file, path-injectable so tests never touch the
 * real store. Three properties the spec does not hand you for free and a
 * naive implementation gets wrong:
 *
 * IDEMPOTENCY. Spec 6.4 gives every Message a `messageId`, generated by the
 * sender. A client that retries a `message/send` after a timeout must not
 * spawn a second task for work already accepted — `findByMessageId` is
 * checked before a new task is created, so the same id always resolves to
 * the same task.
 *
 * THREADING. `contextId` groups a multi-turn conversation (spec 6.1, 6.4).
 * A second message carrying a contextId whose task is still open (not in a
 * terminal state) is appended to that task's history rather than starting a
 * new one — the same session keeps the thread instead of forking a new task
 * per reply.
 *
 * BOUNDED AND EXPIRED. Capped at 500 tasks; terminal tasks older than 7 days
 * are swept by `cleanupExpired`. Eviction prefers the oldest TERMINAL task
 * over the oldest task outright, so a burst of short-lived tasks does not
 * push out something still `working`.
 */

import { randomBytes } from "node:crypto";
import { join } from "node:path";
import { homedir } from "node:os";
import { loadJson, saveJson } from "../core/json-store.js";
import { log } from "../core/log.js";
import type { TaskState } from "./schema/types.js";

export type { TaskState } from "./schema/types.js";

const TERMINAL: ReadonlySet<TaskState> = new Set(["completed", "canceled", "failed", "rejected"]);

export interface TaskHistoryEntry {
  role: "user" | "agent";
  text: string;
  messageId: string;
  at: string;
}

export interface TaskArtifactEntry {
  artifactId: string;
  name?: string;
  text: string;
  /** Set when the artifact's text was validated as an AG2 message and passed. */
  agentishOk?: boolean;
}

export interface A2ATask {
  id: string;
  contextId: string;
  /** The exposed session this task was addressed to. */
  session: string;
  state: TaskState;
  statusMessage?: string;
  createdAt: string;
  updatedAt: string;
  history: TaskHistoryEntry[];
  artifacts: TaskArtifactEntry[];
}

interface Store { tasks: A2ATask[] }

const MAX_TASKS = 500;
const EXPIRY_MS = 7 * 24 * 60 * 60 * 1000;

export function defaultTaskFile(): string {
  return join(homedir(), ".aibroker", "a2a-tasks.json");
}

function read(file: string): Store {
  const r = loadJson<Store>(file);
  if (r.status === "ok" && Array.isArray(r.data?.tasks)) return r.data;
  if (r.status === "unreadable") {
    log(`a2a-tasks: ${file} is unreadable — proceeding as if it were empty for this call, same fail-open behaviour as the other JSON stores here`);
  }
  return { tasks: [] };
}

function write(file: string, s: Store): void {
  saveJson(file, s);
}

function newId(prefix: string): string {
  return `${prefix}-${Date.now().toString(36)}-${randomBytes(4).toString("hex")}`;
}

/** Drop tasks past the bound, oldest terminal task first. */
function enforceBound(s: Store): void {
  while (s.tasks.length > MAX_TASKS) {
    const idx = s.tasks.findIndex((t) => TERMINAL.has(t.state));
    s.tasks.splice(idx >= 0 ? idx : 0, 1);
  }
}

export function findByMessageId(messageId: string, file: string = defaultTaskFile()): A2ATask | undefined {
  const s = read(file);
  return s.tasks.find((t) => t.history.some((h) => h.messageId === messageId));
}

export function getTask(id: string, file: string = defaultTaskFile()): A2ATask | undefined {
  return read(file).tasks.find((t) => t.id === id);
}

export function listForSession(session: string, file: string = defaultTaskFile()): A2ATask[] {
  const want = session.trim().toLowerCase();
  return read(file).tasks.filter((t) => t.session.toLowerCase() === want);
}

export function listAll(file: string = defaultTaskFile()): A2ATask[] {
  return read(file).tasks;
}

export interface CreateOrThreadResult {
  task: A2ATask;
  /** False when an existing open task on the same contextId was reused. */
  created: boolean;
}

/**
 * Create a task for `session`, or thread onto an existing open one sharing
 * `contextId`, or return the task a repeated `messageId` already produced.
 */
export function createOrThreadTask(opts: {
  session: string;
  text: string;
  messageId: string;
  contextId?: string;
}, file: string = defaultTaskFile()): CreateOrThreadResult {
  const s = read(file);

  const dup = s.tasks.find((t) => t.history.some((h) => h.messageId === opts.messageId));
  if (dup) return { task: dup, created: false };

  const openInContext = opts.contextId
    ? s.tasks.find((t) => t.contextId === opts.contextId && !TERMINAL.has(t.state))
    : undefined;

  const now = new Date().toISOString();
  const entry: TaskHistoryEntry = { role: "user", text: opts.text, messageId: opts.messageId, at: now };

  if (openInContext) {
    openInContext.history.push(entry);
    openInContext.updatedAt = now;
    // A follow-up on a task already answered re-opens it for work rather
    // than being silently appended to a task nothing is watching.
    if (openInContext.state === "input-required") openInContext.state = "working";
    write(file, s);
    return { task: openInContext, created: false };
  }

  const task: A2ATask = {
    id: newId("a2a"),
    contextId: opts.contextId ?? newId("ctx"),
    session: opts.session,
    state: "submitted",
    createdAt: now,
    updatedAt: now,
    history: [entry],
    artifacts: [],
  };
  s.tasks.push(task);
  enforceBound(s);
  write(file, s);
  return { task, created: true };
}

export function setStatus(
  id: string,
  state: TaskState,
  opts: { message?: string } = {},
  file: string = defaultTaskFile(),
): A2ATask | undefined {
  const s = read(file);
  const task = s.tasks.find((t) => t.id === id);
  if (!task) return undefined;
  task.state = state;
  if (opts.message !== undefined) task.statusMessage = opts.message;
  task.updatedAt = new Date().toISOString();
  write(file, s);
  return task;
}

export function addArtifact(
  id: string,
  text: string,
  opts: { name?: string; agentishOk?: boolean } = {},
  file: string = defaultTaskFile(),
): A2ATask | undefined {
  const s = read(file);
  const task = s.tasks.find((t) => t.id === id);
  if (!task) return undefined;
  task.artifacts.push({ artifactId: newId("art"), name: opts.name, text, agentishOk: opts.agentishOk });
  task.history.push({ role: "agent", text, messageId: newId("msg"), at: new Date().toISOString() });
  task.updatedAt = new Date().toISOString();
  write(file, s);
  return task;
}

/** Remove terminal tasks past EXPIRY_MS. Returns how many were removed. */
export function cleanupExpired(file: string = defaultTaskFile(), now: number = Date.now()): number {
  const s = read(file);
  const before = s.tasks.length;
  s.tasks = s.tasks.filter((t) => {
    if (!TERMINAL.has(t.state)) return true;
    return now - Date.parse(t.updatedAt) < EXPIRY_MS;
  });
  const removed = before - s.tasks.length;
  if (removed > 0) write(file, s);
  return removed;
}
